### PR TITLE
Added option for developer to add Release versions. 

### PR DESCRIPTION
**Pull request by schroef**
This will show the Title as version number. Using releases is much smaller as nothing of the repository itself is downloaded. These being readme.md, licenses and possible all other folders like image, wiki or any other folder. Thus makes the update faster and way smaller, also is much cleaner in the Blender addon folder after the update.

In the example below the release file 400Kb where as the complete branch repo is 5Mb. Much faster and cleaner!

Now it shows titles of the releases as well and downloads the much smaller zip files
screen shot 2018-02-14 at 1 04 33 am

As how it shows in blender addon
screen shot 2018-02-14 at 1 03 59 am

### CODE REVIEW

**Comment by schroef** [comment]
I forgot small thing, ive change the update panel as how it shows. Also my version has editted _overwrite_patterns. 

screen shot 2018-02-14 at 1 01 58 am
See below example of my panel version

**Comment by TheDuckCow** [comment]
Thanks for the PR! Did a quick look - overall looks good, I'll just want to play with it a little further to test it, and make sure it stays consistent with behavior for GitLab & BitBucket. You beat me to taking one of the first steps to getting release logs natively in the updater panel, which we can get from the release json response.

For what you are doing with assets, I may need to still poke and see what you're repo and requests look like because it doesn't translate immediately to this one's, e.g. lines like `link = self._tags[0]["assets"][0]["browser_download_url"]` and related. I think I get the point, it's selecting which actual download to include, just need to see where it is also in practice to test the calls/responses and think of the best way to represent it through config options.

I see you changed some of the settings which would be for your render addon e.g. the updater.user and updater.addon values and such, well those would be good to revert back to the defaults of the updater demo itself. I can do that or if you want to, feel free - just check the diff :)

For the left-right, I do like it - just have to weigh which is better for more universal use e.g. the two columns might be a little wide for the 3D view-toolshelf... but I suppose the developer could modify their draw method if too narrow.

Good idea on full release names. I might make that into an option to show tag names versus full title as in some cases it might be nice to have the cleaner/shorter version names.

**Comment by schroef** [comment]
>  may need to still poke and see what you're repo and requests look like because it doesn't translate immediately to this one's,

Im not sure i get the part what you mean by, im none english speaking :) I had a hard time understand why this link url needed to be that long, took me a while to get this to work properly. If user has no releases, than the assets part is empty. Also i dont know if this works for the others like bitbucket and githublab. Didnt test those as im not using them.

Sorry for not cleaning it out properly, indeed the 2 column is for my personal likings. Im using for a different render engine. So to me the most logic place would be near the render tab buttons.

**Comment by schroef** [comment]
Well i noticed one thing, if the user uses releases but doesnt add a zip. Than my setup wont work. I set it up that it looks for items in /releases/download/ those are items you can add as binaries.

Otherwise, a releases is just the same as the other and it will download a full repo including all the other files, just like branch and tags.

screen shot 2018-02-14 at 9 00 13 am

**Comment by TheDuckCow** [comment]
Still working on merging the code, but I see now why the zip is so large by default for you - it's because it's including the wiki files, which is [part of the repository](https://github.com/grakoczy/TheaForBlender/tree/master/wiki). 

Irrelevant to the points here, I might recommend compressing the two largest images on the wiki, namely [this file (2.7MB)](https://github.com/grakoczy/TheaForBlender/blob/master/wiki/images/full_blender_screenshot.png) and [this file (~1MB)](https://github.com/grakoczy/TheaForBlender/blob/master/wiki/images/image11.png). Compressing to jpegs or even compressing the PNG's themselves would be able to bring the combined 3.7 to <1MB imo, which is regardless good for page loading. Anyways, just a suggestion - cheers!

Also just to say it, I have at least one other developer who was looking in how to include custom builds per OS (e.g. if using cython and needing to distribute specific builds for mac, linux, and windows separately). Just letting you know your contribution in the PR here gets 70% of the way to being able to do that, so thanks again!

**Pull request merged**
