### PR TITLE
Support Blender 2.8

### PR DESCRIPTION
**Pull request by nutti**
Recently, I updated this script for my script to support Blender 2.8.
This PR fixes the error raised in Blender 2.8.

I also fixed the example of this project as well.

### CODE REVIEW

**Comment by TheDuckCow** [comment]
Appreciate the proactive update. I’ll review and make any further changes to get this in. 

One thing to be mindful of: you should make sure your 2.7x users can’t accidentally upgrade to 2.8 code as it will break (and vice versa for downgrading to older versions). You can do this most easily in two ways:

1) set *max* update version for the 2.7x, and then have the 2.8 version be pegged at some major number and higher (eg go from 1.3.6 -> 2.0.0 for blender 2.8), and set this new major number as the new minimum update target for 2.8 code. 

2)  have both 2.7x and 2.8 releases attached to the same releases as additional attachments, so you don’t have the change your versioning and can keep updating brig 2.7x and 2.8 code in parallel. This requires adding some logic to the updater function which pulls attachment zips, but should be easy to do (something that today could already be used to eg distinguish between windows vs Linux vs OSX builds for addons that require it). Let me know if you have questions about this approach. 

Thanks again for the PR!
Patrick

**Comment by Darkblader24** [comment]
I think it would be better to make this addon compatible with 2.79 and 2.8 at the same time. It's not too difficult to achieve that.

**Comment by TheDuckCow** [comment]
Unfortunately that’s not best practice in how 2.8 is setup however, particularly around code styles for property field definitions. 

Right now using class property definitions with equal signs generates warnings when the addon registers, but in the future these will be seen as errors with addons failing to register (I’m not sure when that exactly will happen). Unfortunately this syntax notation for python fields isn’t recognized in the versions of python pre 2.8 builds ship with, hence the break in backwards compatibility. 

I could see a scenario of doing “if/else” or try catch checking to see the version of python and then accordingly use the appropriate class field definition method, but that’s quite an anti-pattern to be putting all over the place. Other than this however I agree the rest should work the same for both 2.8 as in 2.7. 

Let me know if you have any differing thoughts around field definitions.

**Review by TheDuckCow — APPROVED** [review]
Thanks for making the initial changes here, I will marge this into master after creating the appropriate 2.79x branch.

**Comment by nutti** [comment]
Thanks for reviewing and feedbacks.

> I think it would be better to make this addon compatible with 2.79 and 2.8 at the same time. 

> Right now using class property definitions with equal signs generates warnings when the addon registers, but in the future these will be seen as errors with addons failing to register (I’m not sure when that exactly will happen). Unfortunately this syntax notation for python fields isn’t recognized in the versions of python pre 2.8 builds ship with, hence the break in backwards compatibility.

I agree with you. I think these limitations makes us difficult to make compatible between 2.7x and 2.8.
One of my solution is selecting classes which will be registered to Blender 2.8. But this solution needs multiple class difinitions for Blender 2.7x and Blender 2.8.
I'm also searching the other solution to get over this problem.

**Comment by Darkblader24** [comment]
I want to create a pull request sometime tomorrow with all the changes necessary to make this work in both versions. It would be great to have this merged into master until then, because I can't create a pull request for this pull request.

**Comment by TheDuckCow** [comment]
Please give me a day or two - I have some other changes I just merged before I merge this PR. I’m not sure I agree with code duplication to have multiple classes, but if you do hear of what others are doing and how they are approaching maintaining both, I’m happy to hear the point of view. Im also chatting on one of the blender IRCs about this and best practices.    


Ultimately, I see it that the blender foundation long term isn’t meaning to try to have developers maintain code that is both pre and post blender 2.8 compatible (there may be more changes down the road) which means it would come down to having dedicated branches for each. Ultimately, a user is only going to download one or the other. As for the developer, if fully using got branches you can further minimize the impact by pull general changes from one branch into another and then just doing the minor changes to make it compatible for that branch (ie adding or removing annotations and other changes user pref access(.preferences vs .user_preferences).   


In a day or two I’ll come back and decide after consulting some others the direction to take this repo, but I am strongly leaning towards parallel branches (with version number ranges dedicated to each branch and sequential version numbers within those branches, much like how older operating systems may be patched for bugs).

**Comment by Darkblader24** [comment]
I created a new PR: #49 

> Please give me a day or two - I have some other changes I just merged before I merge this PR. I’m not sure I agree with code duplication to have multiple classes, but if you do hear of what others are doing and how they are approaching maintaining both, I’m happy to hear the point of view. Im also chatting on one of the blender IRCs about this and best practices.

I didn't meant to create hurry, I'm sorry. Also there will be no code duplication added by my PR.

I think it would be much better to make this addon compatible for both Blender versions, because you would give addon creators a choice if they want to make their addon support both Blender versions or not. Otherwise they are forced to make two versions or apply all the neccessary changes to the updater themselves.

**Comment by TheDuckCow** [comment]
Thanks for the PR, and no worries more just didn’t want you to do unnecessary work. That being said, I do like your solution - sure a bit of an anti pattern, but for the minimal code change and multi blender version support I think this is fair (and far better than what I initially thought you meant). May adopt it myself in some other places too...

At a glance the code changes look good, I’ll work on  merging and creating a new update, noting I have pushed a couple other good changes to be included in v1.0.6 that you’ll want to grab (or just check the latest master, it’s there now already). 

Thanks both of your for jumping in here!

**Comment by nutti** [comment]
> I think it would be much better to make this addon compatible for both Blender versions, because you would give addon creators a choice if they want to make their addon support both Blender versions or not.

Thanks for giving the solution.
It is a good solution and I would like to refer your implemetation for my other projects.

**Comment by Darkblader24** [comment]
I'm happy to help, use it wherever you want.

**Comment by schroef** [comment]
> I created a new PR: #49
> 
> > Please give me a day or two - I have some other changes I just merged before I merge this PR. I’m not sure I agree with code duplication to have multiple classes, but if you do hear of what others are doing and how they are approaching maintaining both, I’m happy to hear the point of view. Im also chatting on one of the blender IRCs about this and best practices.
> 
> I didn't meant to create hurry, I'm sorry. Also there will be no code duplication added by my PR.
> 
> I think it would be much better to make this addon compatible for both Blender versions, because you would give addon creators a choice if they want to make their addon support both Blender versions or not. Otherwise they are forced to make two versions or apply all the necessary changes to the updater themselves.

I dont think this can actually be done, the way addons need to be written and certain changes to the API would mean you would need to write classes double, which only adds to file size.

Main issue is see is how ti register classes and using attributes. both Blender use complete different approach. Another thing is mingling these 2 versions into one makes search/editing for items a hustle as probably tons of code will be double. So where you want or need to edit something 2.79 related specifically, you would than also would need to take good care and looking if your actually working in  the proper class.

**Comment by schroef** [comment]
> Appreciate the proactive update. I’ll review and make any further changes to get this in. One thing to be mindful of: you should make sure your 2.7x users can’t accidentally upgrade to 2.8 code as it will break (and vice versa for downgrading to older versions). You can do this most easily in two ways: 1) set *max* update version for the 2.7x, and then have the 2.8 version be pegged at some major number and higher (eg go from 1.3.6 -> 2.0.0 for blender 2.8), and set this new major number as the new minimum update target for 2.8 code. 2) have both 2.7x and 2.8 releases attached to the same releases as additional attachments, so you don’t have the change your versioning and can keep updating brig 2.7x and 2.8 code in parallel. This requires adding some logic to the updater function which pulls attachment zips, but should be easy to do (something that today could already be used to eg distinguish between windows vs Linux vs OSX builds for addons that require it). Let me know if you have questions about this approach. Thanks again for the PR! Patrick
> […](#)
> On Jan 1, 2019, at 05:13, Nutti ***@***.***> wrote: Recently, I updated this script for my script to support Blender 2.8. This PR fixes the error raised in Blender 2.8. I also fixed the example of this project as well. You can view, comment on, or merge this pull request online at: #48 Commit Summary Support Blender 2.8 File Changes M __init__.py (34) M addon_updater_ops.py (146) Patch Links: https://github.com/CGCookie/blender-addon-updater/pull/48.patch https://github.com/CGCookie/blender-addon-updater/pull/48.diff — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

PS would the option "use_releases" which i addd be in help here. That was sort what i was aiming for than, so user can specify tags. This way you can put a certain tag with info added that A is for 2.80 and say B is for 2.79

Only thing is than, how long would you need to support or keep updating older code. Since for example since the changes to gitHub, this addon doesnt do anything no more for me on OSX.

Wasnt 2.80 going to change this? Can recall it properly, has been a while i worked on this updater
See issue #39

**Comment by schroef** [comment]
PS i just tried 2.80 release of yesterday on OSX and used your test code from [here](https://github.com/CGCookie/blender-addon-updater/issues/39#issuecomment-370111847) to quick test it.

This is what i got, seem to be working again :)
```

OpenSSL 1.1.0i  14 Aug 2018
[{"name":"v1.0.5","zipball_url":"https://api.github.com/repos/CGCookie/blender-addon-updater/zipball/v1.0.5","tarball_url":"https://api.github.com/repos/CGCookie/blender-addon-updater/tarball/v1.0.5","commit":{"sha":"266486fb28d088aa347e86425a1b68ae87102ad1","url":"https://api.github.com/repos/CGCookie/blender-addon-updater/commits/266486fb28d088aa347e86425a1b68ae87102ad1"},"node_id":"MDM6UmVmNTcwNjk3Mzk6djEuMC41"},{"name":"v1.0.4","zipball_url":"https://api.github.com/repos/CGCookie/blender-addon-updater/zipball/v1.0.4","tarball_url":"https://api.github.com/repos/CGCookie/blender-addon-updater/tarball/v1.0.4","commit":{"sha":"84d3bc2ef9e68137c07a90c3f57ffb5a752bbcaf","url":"https://api.github.com/repos/CGCookie/blender-addon-updater/commits/84d3bc2ef9e68137c07a90c3f57ffb5a752bbcaf"},"node_id":"MDM6UmVmNTcwNjk3Mzk6djEuMC40"},{"name":"v1.0.3","zipball_url":"https://api.github.com/repos/CGCookie/blender-addon-updater/zipball/v1.0.3","tarball_url":"https://api.github.com/repos/CGCookie/blender-addon-updater/tarball/v1.0.3","commit":{"sha":"51072e9a4822ddb2faca8d86d1bd98b3b5159c08","url":"https://api.github.com/repos/CGCookie/blender-addon-updater/commits/51072e9a4822ddb2faca8d86d1bd98b3b5159c08"},"node_id":"MDM6UmVmNTcwNjk3Mzk6djEuMC4z"},{"name":"v1.0.2","zipball_url":"https://api.github.com/repos/CGCookie/blender-addon-updater/zipball/v1.0.2","tarball_url":"https://api.github.com/repos/CGCookie/blender-addon-updater/tarball/v1.0.2","commit":{"sha":"6b3297cd87e3f9f49639bd05dff9da04e75c9ba8","url":"https://api.github.com/repos/CGCookie/blender-addon-updater/commits/6b3297cd87e3f9f49639bd05dff9da04e75c9ba8"},"node_id":"MDM6UmVmNTcwNjk3Mzk6djEuMC4y"},{"name":"v1.0.1","zipball_url":"https://api.github.com/repos/CGCookie/blender-addon-updater/zipball/v1.0.1","tarball_url":"https://api.github.com/repos/CGCookie/blender-addon-updater/tarball/v1.0.1","commit":{"sha":"76b0a9f31fce1a6404d7497ea365324219a99163","url":"https://api.github.com/repos/CGCookie/blender-addon-updater/commits/76b0a9f31fce1a6404d7497ea365324219a99163"},"node_id":"MDM6UmVmNTcwNjk3Mzk6djEuMC4x"},{"name":"v1.0.0","zipball_url":"https://api.github.com/repos/CGCookie/blender-addon-updater/zipball/v1.0.0","tarball_url":"https://api.github.com/repos/CGCookie/blender-addon-updater/tarball/v1.0.0","commit":{"sha":"3cf47c1d53dc007e1ed0bae0d91b6131cc27ca9d","url":"https://api.github.com/repos/CGCookie/blender-addon-updater/commits/3cf47c1d53dc007e1ed0bae0d91b6131cc27ca9d"},"node_id":"MDM6UmVmNTcwNjk3Mzk6djEuMC4w"}]
RuntimeError: class QS_OT_addon_updater, function execute: incompatible return value , str(, Function.result expected a set, not a NoneType)

location: <unknown location>:-1

location: <unknown location>:-1


```

~~Though something at the end of that code or request does cause an error. It seem that we can pull data again from gitHub~~
I forgot to add a return {'FINISHED'} code runs just fine now

**Comment by schroef** [comment]
> equal signs

~~I believe the classes or functions wont even work without if not done properly.~~
I does work and gives the feedback " make annotation: WORKSPACE_OT_set_layout.wslayoutMenu"

This is just one of them changes i dont get? This method looks like a json approach. I also find the need to add all items in a function with something="ITEM" also to much. We need to add a lot more now with this new API.

**Comment by schroef** [comment]
> Recently, I updated this script for my script to support Blender 2.8.
> This PR fixes the error raised in Blender 2.8.
> 
> I also fixed the example of this project as well.

PS @nutti is i correct this pull isnt in the latest build of BLender 2.80 yet?
I hardly see anything in the addon now?, compared to 2.79

screen shot 2019-01-05 at 01 24 39
screen shot 2019-01-05 at 01 25 09

**Comment by TheDuckCow** [comment]
Yes I haven’t merged his latest code yet, still reviewing and want to make sure the right direction is taken (been busy with some other work so apologies for the delay). Re code duplication: the more recent PR actually prevents any code duplication by using 2.7x form of property definition and then after the fact applying the annotation attribute via setattr. I just need to see for myself this work correctly and prevents the registration warnings. 

Note that I also confirmed on the Blender IRC chat that, as of right now, there is no planned timeline as to when these annotation warnings will change to errors. See here: https://blender.chat/channel/python

Also correct, the updater does indeed work on blender 2.8 for OSX (actually, it’s worked on OSX blender 2.79 dev releases for awhile, just not the master releases). This is again all due to the version of *python* that is bundled with blender and that more recent releases of 2.79 dev and any 2.8 build have more recent python and thus ssl libraries.

**Comment by schroef** [comment]
@TheDuckCow 
I was looking at the MagicUV repo and didnt see this pull. I understand its not here untill its merged.

I also have a couple addons which im converting now. Had a couple bug the crap out of me since so many things has changed. My main bugger will be the external render engine im maintaining. Thats a couple py files and some contain 5-6k lines of code?!?!?! 

I did 2 addons now and one which was about 200 lines of code already took me days to get it working. Im just to scared to start on the other now :(

**Comment by nutti** [comment]
@schroef 

> i correct this pull isnt in the latest build of BLender 2.80 yet?
> I hardly see anything in the addon now?, compared to 2.79

I think my blender version is old.
I'm now rewriting whole scripts to work in the latest blender build.


@TheDuckCow  @Darkblader24 

There are two versions in the PR now. (The another one is #49 )
I think it needs additional work to merge these into master branch.
If you don't mind, I will merge the revision on #49 and recommit to this PR.
What do you think about this idea?

And I confirmed that the revision of #49 works in my another project.

**Comment by TheDuckCow** [comment]
Thanks, I can take it from here - there's a couple style things I'm going to adjust but will be functionally the same. I'll see what I can do to merge and push it as an update towards the end of the week.

**Review by TheDuckCow — APPROVED** [review]
Will approve and merge this PR and then PR https://github.com/CGCookie/blender-addon-updater/pull/49 secondly to merge both pieces. Will address further changes by committing to master.

**Comment by TheDuckCow** [comment]
Thanks again both @nutti and @Darkblader24 for your assistance! I believe everything is merged in now, plus some additional changes I have made. Feel free to comment or open suggestion issues if you think anything should be different. I have actively tested and found the current version of the master indeed works in both 2.7x and 2.8x.

Also might be worth pointing out how I skip around needing to add the annotation wrappers to each class, and instead simplified the registration process which is a better practice anyways.

**Comment by nutti** [comment]
Thanks. It is good news for us to support this script for Blender 2.8.

**Comment by schroef** [comment]
Does someone know where i can find more info about @ make_annotations i would like to understand what this actually does.

**Comment by schroef** [comment]
Ow i see it now, i changes the properties, changing = > : 
Thats nice, man thats looks like clever coding. WIsh i new stuff like that

**Pull request merged**
