### PR TITLE
Feature Pep8 pass

### PR DESCRIPTION
**Pull request by neomonkeus**
Apply pep8 formatting to code base
- Prefer pythonic style checks for expressions, such as is none
- Classes automatically inherit object, so remove explicit object per pep8 convention.
- Use bl_idname to apply Blender name convention rather than class, as pep doesn't like it

Note:
Made a backwards in compatible change by renaming `updater_intrval_minutes` to `updater_interval_minutes`.
- If you want I can revert that out to keep it backwards compatible for this version and do follow with minor/major version to denote that.
- Keep in and bump the version number to a full minor version
Open to whatever you feel is appropriate, but again most developers are copy-pasting as we talked about previously so not a huge fix to account for when upgrading.

### CODE REVIEW

**Comment by neomonkeus** [comment]
@TheDuckCow Meant to open this eons ago.
Sorry if this is quiet large, but this should apply pep8 to the code base. 

I left this as a draft for now as wanted to get your initial feedback and also may need to rebase for any changes that you made to this repo since i originally cloned the repo, I don't think I kept the branch up to date.

**Comment by neomonkeus** [comment]
So I did a rebase and doesn't look like there is anything that was added since. 
However looks like when I made this PR I selected the wrong source branch and I don't have permissions to retarget.
Can you retarget it to develop.

**Comment by TheDuckCow** [comment]
Hi there, thanks for pulling this together. Just to be very explicit, as you understand, there have been no functionality changes here? Just for reference, did you use automated tools or manual changes to make the updates? Helps as I consider merging the changes. I appreciate the contributions!

In terms of branch, there's only a master branch on this repo so that should be all good.

> If you want I can revert that out to keep it backwards compatible for this version and do follow with minor/major version to denote that.

Appreciate calling that out! Let me think on it - in some cases I've actually just defined two versions and had the old point to the new to maintain backwards, but definitely introduces a bit of bloat since it's a simple rename. I think it would be also fair to just flag this in release notes, good spelling is a good thing and in any regards any code should be self consistent at one snapshot of time more so than between snapshots (if we are talking about someone who updates their addon updater and users go through the update experience, they should restart blender anyways to fully reload the code).

**Comment by neomonkeus** [comment]
> Hi there, thanks for pulling this together. Just to be very explicit, as you understand, there have been no functionality changes here? Just for reference, did you use automated tools or manual changes to make the updates? Helps as I consider merging the changes. I appreciate the contributions!
> 

I ran it through pep8 auto-formatting with Intellij. 
For the most part it will apply things like, 
- consistency of spacing around params, brancket, operators.
- pythonic phrasing: using `is` `not`, removing `== True`.
- Prefer isinstance rather than type comparison 

There are still parts which are somewhat subjective like:
- Method params, keeping them on the same line vs splitting them multi-line.
- Whether or not to adhere to line length 80

Functionally, no there have been no changes, the only change as pointed as was a spelling correction.
- renaming updater_intrval_minutes to updater_interval_minutes, 

> In terms of branch, there's only a master branch on this repo so that should be all good.
>
Sorry the issue is actually a result from how I opened the PR
Rathern than `CGCookie:master from neomonkeus:feature/pep_pass` it should be `CGCookie:master from neomonkeus:develop`
This is isn't something I can fix on my side, you should be able to edit it.

> Appreciate calling that out! Let me think on it - in some cases I've actually just defined two versions and had the old point to the new to maintain backwards, but definitely introduces a bit of bloat since it's a simple rename. I think it would be also fair to just flag this in release notes, good spelling is a good thing and in any regards any code should be self consistent at one snapshot of time more so than between snapshots (if we are talking about someone who updates their addon updater and users go through the update experience, they should restart blender anyways to fully reload the code).
>
Happy to go either route as I can kick that bit out, then do a subsequent PR for that specific update.

**Pull request closed without merging**
