### PR TITLE
Format with PEP8

### PR DESCRIPTION
**Pull request by johnroper100**

### CODE REVIEW

**Comment by TheDuckCow** [comment]
Outside of changing tabs to spaces, what changes are made? It's hard to see as it is

**Comment by johnroper100** [comment]
This is just making the code conform to the PEP8 formatting standards. This is required for add-ons to be included in Blender, but also, it is just a good thing to do.

**Comment by johnroper100** [comment]
PEP8 is the official python style and convention guide. https://www.python.org/dev/peps/pep-0008/

**Comment by TheDuckCow** [comment]
I am aware, though as per PEP8 guidelines itself, spaces are recommended over tabs but is still largely a recommendation. It is up to the individual addon developer to ensure code is consistent throughout, tabs vs spaces. I tend to prefer to by hand ensure readability and no weird line breaks is maintained rather than run through auto PEP8 converters. 

https://www.python.org/dev/peps/pep-0008/#id18

**Pull request closed without merging**
