### PR TITLE
Fix: failed to update with deep directories

### PR DESCRIPTION
**Pull request by nutti**
Currently, this script failed to update the add-on whose top level ```__init__.py``` is located on the deep directory (more than 2 level directory).

#### Failed case

```
dir_1 --- dir_2 --- __init__.py
dir_1 --- dir_2 --- dir_3 --- __init__.py
```

This patch enable to search ```__init__.py``` recursively, so we can update add-on which has more than 2 level directory.

This patch also enables you to specify the maximum recursive search level by  ```updater.max_directory_level```.

Thanks.

### CODE REVIEW

**Comment by TheDuckCow** [comment]
Hello, I think you may actually be interested in a recent contribution into the dev branch of the updater. The code is already in place, and implements more explicitly the location of the __init__.py file; the setting is defaulted to updater.subfolder_path = "”, but you can set the path to an explicit sub folder. 

Let me know if that happens to work for you. I think it is better to allow for explicit folder declaration rather than allow recursion to multiple folders deep. 

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com

**Comment by nutti** [comment]
Thanks for your information.
I did not notice the develop branch.

Now, I tried it and worked great.
I think ```updater.subfolder_path``` is better solution than mine.
So, please discard my revision.

Before closing this PR, I would like to know the release date which includes ```subfolder_path``` option.
If this patch is released, I will use this script for my add-on.

Thanks

**Comment by TheDuckCow** [comment]
The aim is for this weekend, it will come out as version 1.0.5, check back here maybe Sunday or Monday - https://github.com/CGCookie/blender-addon-updater/releases

**Comment by nutti** [comment]
OK, thanks.

**Pull request closed without merging**
