### PR TITLE
Issue #4 Add support for Bitbucket

### PR DESCRIPTION
**Pull request by blanchg**
This is my initial support for bitbucket.  It is working for v7.4.0 of https://bitbucket.org/coronablender/render_corona

Thanks for your efforts, it was nearly trivial to adapt to bitbucket :)

Changing the engine is all that is required:
`updater.engine = addon_updater_github.engine`
or
`updater.engine = addon_updater_blender.engine`

### CODE REVIEW

**Comment by TheDuckCow** [comment]
This looks great! I like the engine structure, good idea. Timing is also great as I'm close to bringing in changes to support gitlab as well. I'll do some testing and then then look to merge. 

One thing I want to figure out is the best way to support the engines. Right now you have files for each, which could work, though could require another step for the developer looking to integrate to delete/add files and also change relating import statements - I know, not hard at all but nonetheless. What are your thoughts of defining those engine classes all within the Updater.py file itself? I can see it either way. We could also just have one engines file.

**Comment by blanchg** [comment]
I have no preference, I do like the idea that there are fewer files to maintain/copy.  Having all the changes in the one file also helps if you need to update without fear of overwriting any hard coded settings.

**Comment by blanchg** [comment]
Combined the two engines into the updater.
Fixed error if offline
Added backup ignore patterns

**Comment by TheDuckCow** [comment]
Awesome, thanks for the quick changes there - will review soon as I can and run through the test cases.

**Comment by TheDuckCow** [comment]
Everything looks pretty good and works from my testing back against github, but one question - is there a particular reason for changing from `context.user_preferences....` over to `bpy.context.user_preferences...` below?

https://github.com/CGCookie/blender-addon-updater/compare/master...blanchg:bitbucket#diff-59a84a958bbe9b22468107144e433486L560

Generally I try to always grab items from the context module and not through bpy, but if there's a good reason to we can do that (and thus, as your change has it, we could remove "context" as an input argument to `check_for_update_background()` ). I could see that if you have a draw function which doesn't have access to context directly.

**Comment by TheDuckCow** [comment]
@blanchg I've merged your work into dev, thank you very much for the useful contribution! My last question is a minor point, but I am now thinking there isn't harm in that scenario to using bpy.context since the addon modules are universal anyways. Shortly I intend on extending and adding gitlab support and then this will come out in the next master release version.

**Comment by blanchg** [comment]
Thanks for that. Yes it was so it could be called without a context. Some
of the unit testing for my plugin may not have a complete context but you
are right I could have just passed boy.context in those cases.

**Pull request merged**
